pipeline {
    agent any
    stages {
        stage('Compile from source') {
            steps {
                script {
                    sh './gradlew clean build'
                }
            }
        }
    }
}
