pipeline {
    agent any
    environment {

    }
    stages {
        stage('Enable permissions for gradlew') {
            steps {
                script {
                    sh 'chmod +x gradlew'
                }
            }
        }
        stage('Compile from source') {
            steps {
                script {
                    sh './gradlew clean build --no-daemon'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'build/libs/**/*.jar', fingerprint: true
        }
    }
}
